_wandb:
    value:
        cli_version: 0.22.1
        e:
            xv6aav8efjgik6gz2gy0ue53mdkkpcwf:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "263816892416"
                        used: "187028029440"
                email: patryklorenc@student.agh.edu.pl
                executable: /home/patryk/Desktop/venv/ML_venv/bin/python
                git:
                    commit: 392695c30c100183043fa526cb437e7c417af4b5
                    remote: https://github.com/PaprykVegee/AiR_ISS.git
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-8998eacd-0602-edab-bf3a-d74fac132c11
                host: patryk-Legion-Y540-15IRH
                memory:
                    total: "33560879104"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: vit_todo-jvsc-f35ccaa7-63eb-4ed9-b31d-533d6db06041a32cb7bd-d9ee-49b5-a2f5-ccd7739cb039.ipynb
                python: CPython 3.10.12
                root: /home/patryk/Desktop/AiR_ISS/sem2/DSN
                startedAt: "2025-10-20T08:59:42.101328Z"
                writerId: xv6aav8efjgik6gz2gy0ue53mdkkpcwf
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.1
            "6": 4.56.2
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
