_wandb:
    value:
        cli_version: 0.22.1
        e:
            zrc63jdnazwkoad5cwwyb3zvq632c6bg:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "263816892416"
                        used: "180434984960"
                email: patryklorenc@student.agh.edu.pl
                executable: /home/patryk/Desktop/venv/ML_venv/bin/python3
                git:
                    commit: 07fd421ee3446040646494f25f75d58743c35107
                    remote: https://github.com/PaprykVegee/AiR_ISS.git
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-8998eacd-0602-edab-bf3a-d74fac132c11
                host: patryk-Legion-Y540-15IRH
                memory:
                    total: "33560879104"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: part1_todo-jvsc-9ec0db96-799b-4db8-be1e-a28d73351a1c7d04cf11-13a0-4985-897a-60fe2c1d60c1.ipynb
                python: CPython 3.10.12
                root: /home/patryk/Desktop/AiR_ISS/sem2/DSN
                startedAt: "2025-10-13T09:00:38.774834Z"
                writerId: zrc63jdnazwkoad5cwwyb3zvq632c6bg
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
